language: node_js
node_js:
- '10'
script:
- npm test
- npm run style
notifications:
  slack:
    rooms:
      secure: jLFBuFJslZpGPe1+oWoEVKh6ZoSxV0u1lGoVLy7V7idpQO1cowpUy7vwcHkhQBfVXUdMfUTrqtWaYhtIqRsyoMzrTxMxoj7IoHUcM7Cluam5R1GFY7TVikK3PXdj1V8BBNOdThS/StNlsOQ9HdlHyhKEZ/L7GjfSDPQsnrCavnBZux1vrEDjJrl5WrPMBfHSIVT1PhxO2wpAWQxaGbEo9LieRxCk+2eP0DNBn8QVrbYd+pUAMDpXslGDozTAyLyu54VQqPsbZJmoAj6qBkPW0yL6RYNItt7vNtBDXPhf01Erji+nTLUoDjPqk378vCJq5DLQQdWGAXp0a1R3+QerH1ZCCfCt9pKhxMdgxy9ysIINWClHQZ7sJeXhkmzxsHaUS5faZSYfMSEIPZk7vQmdwJARFv8VsBbQljmdlcBBHiEyM+ARp+xoxUikEhTdyoX/TVpaOKVfGk41uOBr+fM4cUDRdT4NLpxoRCNtWj/X366JimOKVua8d8bUqvp9SdGjmj8nrE9ihTsi0j2u8iPBZCWuOhNQBl02Nlp1FteLdsOBJJ/yz/UHHqibnj+ahnoyk4sklmOeg2Zvm9RUIbp87RFdAucvFmUz2fkDcE0l87pwO94d060Z57tvwWjBQi0EUuQxMzkphYbO1NRmASKbn5gr1X9SlwrvCpikSxtVsg0=
    on_success: always
    on_failure: always
