language: node_js
node_js:
  - '10'

#services:
#  - postgresql

#before_script:
#  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm test
  - npm run style


notifications:
  slack:
    rooms:
      secure: jLFBuFJslZpGPe1+oWoEVKh6ZoSxV0u1lGoVLy7V7idpQO1cowpUy7vwcHkhQBfVXUdMfUTrqtWaYhtIqRsyoMzrTxMxoj7IoHUcM7Cluam5R1GFY7TVikK3PXdj1V8BBNOdThS/StNlsOQ9HdlHyhKEZ/L7GjfSDPQsnrCavnBZux1vrEDjJrl5WrPMBfHSIVT1PhxO2wpAWQxaGbEo9LieRxCk+2eP0DNBn8QVrbYd+pUAMDpXslGDozTAyLyu54VQqPsbZJmoAj6qBkPW0yL6RYNItt7vNtBDXPhf01Erji+nTLUoDjPqk378vCJq5DLQQdWGAXp0a1R3+QerH1ZCCfCt9pKhxMdgxy9ysIINWClHQZ7sJeXhkmzxsHaUS5faZSYfMSEIPZk7vQmdwJARFv8VsBbQljmdlcBBHiEyM+ARp+xoxUikEhTdyoX/TVpaOKVfGk41uOBr+fM4cUDRdT4NLpxoRCNtWj/X366JimOKVua8d8bUqvp9SdGjmj8nrE9ihTsi0j2u8iPBZCWuOhNQBl02Nlp1FteLdsOBJJ/yz/UHHqibnj+ahnoyk4sklmOeg2Zvm9RUIbp87RFdAucvFmUz2fkDcE0l87pwO94d060Z57tvwWjBQi0EUuQxMzkphYbO1NRmASKbn5gr1X9SlwrvCpikSxtVsg0=
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: ATtA2+AXcaVYUkyVAoAp6k6o8uElskYSaMOgDEnnlcc1Y85N3grOecy9nKQme+17E+rd90m4MDAWBQ5WKCP+lbZVuLSQy4Iktb8Wns3LSuH1BbRQnO49VkaviCVNbzvnUvJD7FeXO6Mj3L2RlCgnVczj+Ask+unwrGkVp0Wag810c70BgO0QKlyZTJibExHvSnBCtbvwr5MDoCvHZ7zQ8WvbHXfectB5s5swvaLluPtU5dybLkeQA1LZE0CTOKDfnhd5+beaxLrQDlHMu6QkDYdsDJCn6eyK/VhJ/gVLIJ/BqJp49Sp8RbvFkWoMesJsYW3IpUVOUx05/no8e1VLQzbiyTtnyG7wF139bxP/vTi/4P9v/i/3gakcPo3fBEWI7hX09JhrnXr3v4wMMzTqK7cfk/QyNcYMxnyoBTrSfKoPN8fDls8zcnnzztwEf3lTQUFTMbVgPpFr8BQtxbqD6gbWvoDQzN/VSTI2u+WO9ozq8TyOFE1cWfr8rCGZrc8vnfINk5N06S5zz3vRZqGZBMayYqbiRkJqTOeUNyr7JRr9iM+433Cg6PchR8OKKtbK5xLt5N75f6ZzMzZqQmZulSjPSTjx4o9O7ha49HQHCUEjjjJ+Gbq4kbesmUr4vxyC68OU6GdtiOy944Ip0T/B3+pH1lxccYJbd7cT+s7lR3E=

  on:
    all_branches: true
